---
events:

  reinforce2020:
    label: 'Reinforce Conference 2020'
    date: 'April 6-7, 2020'
    dates:
      - ticket-name-contains: "Workshop"
        date: "April 8, 2020"
      - ticket-name-contains: "*"
        date: "April 6-7, 2020"
    invoice:
      id-prefix: "RF"
      logo-image: "RF-szamlazzhu.png"
      comment: |
        The invoice includes mediated services.
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true  
    email:
      replyToAddress: "hello@reinforceconf.com"
      subject: "Your invoice for Reinforce Conference 2020"
      message: |
        Dear Attendee!

        Thank you for taking part in Reinforce AI Conference 2020.

        Please find attached our official invoice for the Reinforce AI conference.
        In case you have an issue with the invoice please reply to this e-mail.
        In case you have a general question regarding the conference please write to: hello@reinforceconf.com

        The Reinforce conference team

    catering:
      - ticket-name-contains: "Diversity"
        net-price: 94.48
      - ticket-name-contains: "Workshop"
        net-price: 23.62
      - ticket-name-contains: "*"
        net-price: 47.24
    bank:
      name: 'Raiffeisen Bank, SWIFT: UBRTHUHB'
      accountNumber: 'HU73-1201-0659-0160-2199-0040-0002'
    tito-token-env: TITO_TOKEN_RF


  integration-test-event-2020:
    label: "JSConf Budapest 2020"
    dates:
      - ticket-name-contains: "*"
        date: "September 24-25, 2020"
    catering:
      - ticket-name-contains: "*"
        net-price: 40
    invoice:
      id-prefix: "WIPAO"
      logo-image: "JSCBP-szamlazzhu.png"
      comment: |
        The invoice includes mediated services.
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: false
    email:
      reply-to-address: "nec@jsconfbp.com"
      subject: "Your invoice for Integration Test Event 2020"
      message: |
        Dear Attendee!

        Thank you for taking part in Reinforce AI Conference 2020.

        Please find attached our official invoice for the Reinforce AI conference.
        In case you have an issue with the invoice please reply to this e-mail.
        In case you have a general question regarding the conference please write to: hello@reinforceconf.com

        The Reinforce conference team

    bank:
      name: "Raiffeisen Bank, SWIFT: UBRTHUHB"
      account-number: "HU18-1201-0659-0160-2199-0020-0008"
    tito-token-env: TITO_TOKEN_JS

