---
events:

  craft-conferencee-2021:
    label: 'CraftHub online workshops'
    dates:
      - ticket-name-contains: "Falco"
        date: "November 11, 18, 25, 2020"
      - ticket-name-contains: "Rainsberger"
        date: "November 10, 12, 17, 19, 2020"
    catering:
      - ticket-name-contains: "online"
        net-price: 0
    invoice:
      id-prefix: "RF"
      logo-image: "RF-szamlazzhu.png"
      comment: |
        The invoice includes mediated services.
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
    email:
      replyToAddress: "hello@crafthub.events"
      subject: "Your invoice for your CraftHub online workshop"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for CraftHub's online workshop.

        Please find attached our official invoice for the workshop.
        In case you have an issue with the invoice, or you have a general question
        regarding the workshop please write to: hello@crafthub.events

        The CraftHub team

    bank:
      name: 'Raiffeisen Bank, SWIFT: UBRTHUHB'
      accountNumber: 'HU73-1201-0659-0160-2199-0040-0002'
    tito-signature-validator-env: TITO-TOKEN-ONLINE-WSH


  jsconf-budapest-2021:
    label: "JSConf Budapest 2021"
    dates:
      - ticket-name-contains: "*"
        date: "September 23-24, 2021"
    catering:
      - ticket-name-contains: "*"
        net-price: 98
    invoice:
      id-prefix: "JSCBP"
      logo-image: "JSCBP-szamlazzhu.png"
      comment: |
        The invoice includes mediated services.
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
    email:
      replyToAddress: "hello@crafthub.events"
      subject: "Your invoice for your CraftHub online workshop"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for CraftHub's online workshop.

        Please find attached our official invoice for the workshop.
        In case you have an issue with the invoice, or you have a general question
        regarding the workshop please write to: hello@crafthub.events

        The CraftHub team

    bank:
      name: "Raiffeisen Bank, SWIFT: UBRTHUHB"
      accountNumber: "HU18-1201-0659-0160-2199-0020-0008"
    tito-signature-validator-env: TITO-TOKEN-ONLINE-WSH


  integration-test-event-2020:
    label: "JSConf Budapest 2020"
    dates:
      - ticket-name-contains: "*"
        date: "September 24-25, 2020"
      - ticket-name-contains: "workshop"
        date: "September 23, 2020"
    catering:
      - ticket-name-contains: "workshop"
        net-price: 20
      - ticket-name-contains: "online"
        net-price: 0
      - ticket-name-contains: "*"
        net-price: 40
    invoice:
      id-prefix: "WIPAO"
      logo-image: "JSCBP-szamlazzhu.png"
      comment: |
        The invoice includes mediated services.
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: false
    email:
      reply-to-address: "nec@jsconfbp.com"
      subject: "Your invoice for Integration Test Event 2020"
      message: |
        Dear Attendee!

        Thank you for taking part in Reinforce AI Conference 2020.

        Please find attached our official invoice for the Reinforce AI conference.
        In case you have an issue with the invoice please reply to this e-mail.
        In case you have a general question regarding the conference please write to: hello@reinforceconf.com

        The Reinforce conference team

    bank:
      name: "Raiffeisen Bank, SWIFT: UBRTHUHB"
      account-number: "HU18-1201-0659-0160-2199-0020-0008"
    tito-signature-validator-env: TITO_TOKEN_TESTMODE

